import etcdserverpb.ClusterGrpc;
import etcdserverpb.MaintenanceGrpc;
import etcdserverpb.Rpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args)    {
        ManagedChannel channel = ManagedChannelBuilder.forAddress("172.23.211.103", 2379).usePlaintext().build();
        try {
            ClusterGrpc.ClusterBlockingStub stub = ClusterGrpc.newBlockingStub(channel);
            Rpc.MemberListResponse response = stub.memberList(Rpc.MemberListRequest.getDefaultInstance());
            System.out.println(response.toString());
        } finally {
            channel.shutdown();
        }
    }
}
